name: Generate Issue Report on Close

on:
  issues:
    types: [closed]  # This will run when an issue is closed

jobs:
  generate-md-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Get Issue Data and Generate Report
        run: |
          # Get the issue data
          ISSUE_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
          ISSUE_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $ISSUE_URL)
          
          # Debugging the response from the GitHub API
          echo "ISSUE DATA: $ISSUE_DATA"

          # Check if the data is empty
          if [ -z "$ISSUE_DATA" ]; then
            echo "Error: No data received from GitHub API"
            exit 1
          fi

          # Extract data from the issue (like title, body, labels)
          TITLE=$(echo $ISSUE_DATA | jq -r .title)
          BODY=$(echo $ISSUE_DATA | jq -r .body)
          LABELS=$(echo $ISSUE_DATA | jq -r .labels | jq -r '.[].name' | paste -sd, -)

          # Check if the fields were correctly extracted
          echo "Title: $TITLE"
          echo "Body: $BODY"
          echo "Labels: $LABELS"

          # Extract responses for dropdowns (adjust according to your structure)
          STEAMVR=$(echo "$BODY" | grep -oP 'Steamvr: \K.*')
          MONADO=$(echo "$BODY" | grep -oP 'Monado: \K.*')
          ALVR=$(echo "$BODY" | grep -oP 'ALVR: \K.*')
          WIVRN=$(echo "$BODY" | grep -oP 'WIVRN: \K.*')
          DESCRIPTION=$(echo "$BODY" | grep -oP 'Description: \K.*')
          DATE=$(echo "$BODY" | grep -oP 'Date: \K.*')

          # Debug extracted values
          echo "SteamVR: $STEAMVR"
          echo "Monado: $MONADO"
          echo "ALVR: $ALVR"
          echo "WIVRN: $WIVRN"
          echo "Description: $DESCRIPTION"
          echo "Date: $DATE"

          # Create the Markdown report
          echo "# Issue Report: $TITLE" > issue_report.md
          echo "**Labels**: $LABELS" >> issue_report.md
          echo "## Report" >> issue_report.md
          echo "**SteamVR**: $STEAMVR" >> issue_report.md
          echo "**Monado**: $MONADO" >> issue_report.md
          echo "**ALVR**: $ALVR" >> issue_report.md
          echo "**WIVRN**: $WIVRN" >> issue_report.md
          echo "**Description**: $DESCRIPTION" >> issue_report.md
          echo "**Date**: $DATE" >> issue_report.md

      - name: Commit and Push the Generated Report
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add issue_report.md
          git commit -m "Generate issue report for closed issue #${{ github.event.issue.number }}"
          git push
