name: Game Report
description: Give feedback for a game.
title: "[Rating]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: steamvr
    attributes:
      label: Steamvr
      description: Provide the level of succes using the SteamVR runtime
      options:
        - Perfect
        - Requires manual configuration
        - Playable with graphical/controller issues
        - Unplayable because of graphical/controller issues
        - Crashes or won't start
    validations:
      required: false
  - type: dropdown
    id: monado
    attributes:
      label: Monado
      description: Provide the level of succes using the Monado runtime
      options:
        - Perfect
        - Requires manual configuration
        - Playable with graphical/controller issues
        - Unplayable because of graphical/controller issues
        - Crashes or won't start
    validations:
      required: false
  - type: dropdown
    id: alvr
    attributes:
      label: ALVR
      description: Provide the level of succes using the ALVR runtime
      options:
        - Perfect
        - Requires manual configuration
        - Playable with graphical/controller issues
        - Unplayable because of graphical/controller issues
        - Crashes or won't start
    validations:
      required: false
  - type: dropdown
    id: wivrn
    attributes:
      label: WIVRN
      description: Provide the level of succes using the WIVRN runtime
      options:
        - Perfect
        - Requires manual configuration
        - Playable with graphical/controller issues
        - Unplayable because of graphical/controller issues
        - Crashes or won't start
    validations:
      required: false      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: date
    attributes:
      label: Date  
 
