name: Generate Issue Report on Close
on:
  issues:
    types: [closed]  # Se ejecutará cuando un issue sea cerrado
jobs:
  generate-md-file:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
      - run: |
          echo A comment on body $input
        env:
          BODY: ${{ github.event.issue.body }}
          input: $BODY
      - run: |
          BODY="${{ github.event.issue.body }}"
          etiqueta_inicio="### Steamvr"
          
          # Filtrar el contenido y asignarlo a una variable
          contenido_filtrado=$(echo "$BODY" | sed -n "/$etiqueta_inicio/,/^###/{ /^###/d; p }")
          
          # Imprimir solo el contenido filtrado
          echo "Contenido filtrado: $contenido_filtrado"

          BODY="${{ github.event.issue.body }}"
          input="$BODY"

          etiqueta_inicio="### Steamvr"

          echo "$BODY" | sed -n "/$etiqueta_inicio/,/^###/{ /^###/d; p }" 

          
          cat "${{ github.action_path }}ideas.txt"
          file="${{ github.action_path }}ideas.txt"
          sed -i '$ d' "$file"
          cat "${{ github.action_path }}ideas.txt"
          echo "A comment on body $BODY"
        shell: bash
