name: Append Opinion to Markdown File

on:
  issues:
    types: [closed]

jobs:
  append_opinion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Markdown tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install markdownify

      - name: Extract issue data
        id: extract_data
        run: |
          echo "title=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo -e "body=$(echo ${{ github.event.issue.body }} | sed ':a;N;$!ba;s/\n/\\n/g')" >> $GITHUB_ENV

      - name: Append opinion to Markdown file
        run: |
          FILE_NAME="$(echo '${{ github.event.issue.title }}' | sed -E 's/\\s+/-/g' | tr '[:upper:]' '[:lower:]').md"
          if [ ! -f "$FILE_NAME" ]; then
            echo "Error: Markdown file for the title does not exist: $FILE_NAME"
            exit 1
          fi
          python3 <<EOF
            from datetime import datetime
            import os
            
            # Input variables
            file_name = os.environ.get("FILE_NAME")
            body = os.environ.get("body")
            
            # Example of parsing the body into specific fields
            lines = body.split("\\n")
            steamvr = "Unknown"
            monado = "Unknown"
            alvr = "Unknown"
            wivrn = "Unknown"
            description = "No description provided."
            date = "Unknown"
            for line in lines:
                if line.startswith("### Steamvr"):
                    steamvr = lines[lines.index(line) + 1].strip()
                elif line.startswith("### Monado"):
                    monado = lines[lines.index(line) + 1].strip()
                elif line.startswith("### ALVR"):
                    alvr = lines[lines.index(line) + 1].strip()
                elif line.startswith("### WIVRN"):
                    wivrn = lines[lines.index(line) + 1].strip()
                elif line.startswith("### Description"):
                    description = lines[lines.index(line) + 1].strip()
                elif line.startswith("### Date"):
                    date = lines[lines.index(line) + 1].strip()
            
            # Opinion entry in Markdown format
            new_opinion = f"""
            - **SteamVR**: {steamvr}
              **Monado**: {monado}
              **ALVR**: {alvr}
              **WIVRN**: {wivrn}
              **Date**: {date}
              **Opinion**: {description}
              **Appended on**: {datetime.utcnow().isoformat()}
            """
            
            # Append to the Markdown file
            with open(file_name, "a") as file:
                file.write("\n" + new_opinion)
          EOF

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Appended opinion to ${{ github.event.issue.title }}"
          git push
