name: Generate Issue Report on Close
on:
  issues:
    types: [closed]  # Se ejecutará cuando un issue sea cerrado
jobs:
  generate-md-file:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
      - run: |
          echo A comment on body $BODY
        env:
          BODY: ${{ github.event.issue.body }}
      - run: |
          cat "${{ github.action_path }}ideas.txt"
