venname: Manual Eleventy Execution
on:
  workflow_dispatch:
    inputs:
      testType:
        description: 'Runs npm run to build eleventy site'
        required: true
        default: 'integration'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests
        run: npm run eleventy
